name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install xvfb
        run: sudo apt-get -y install xvfb
      - name: Install openbox
        run: sudo apt-get -y install openbox
      - name: Install scrot
        run: sudo apt-get -y install scrot
      - name: Start xvfb
        run: xvfb-run -e errors.txt openbox &
      - name: Wait
        run: sleep 5
      - name: Screenshot
        run: scrot output.png
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: image
          path: output.png
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: errors
          path: errors.txt
