name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go
        run: .github/workflows/run-xvfb.sh
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: image
          path: output.jpg
